import Head from 'next/head';
import styles from './index.module.css';
import { sourcebitDataClient } from 'sourcebit-target-next';

export default function DynamicPage(props) {
    // console.log(props);
    const { site, page } = props;
    return (
        <div className={styles.container}>
            <Head>
                <title>{site.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>{page.title && <h1 className={styles.title}>{page.title}</h1>}</main>
        </div>
    );
}

export async function getStaticProps({ params }) {
    const pagePath = typeof params?.slug === 'string' ? params?.slug : '/' + (params?.slug || []).join('/');
    const props = await sourcebitDataClient.getStaticPropsForPageAtPath(pagePath);
    return { props };
}

export async function getStaticPaths() {
    const paths = await sourcebitDataClient.getStaticPaths();
    return {
        paths,
        fallback: false
    };
}
